[package]
name = "chasm-cli"
description = "The chasm command-line tool."
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "chasm"
path = "src/main.rs"

[dependencies]
chasm-core.workspace = true
chasm-runtime.workspace = true
clap.workspace = true
lsp-server = "0.10.0"
lsp-types = "0.97.0"
serde.workspace = true
serde_json.workspace = true
