//! Whole-program driver: sources in, diagnostics + word database + module out.

use serde::Serialize;
use std::collections::{HashMap, HashSet};

use crate::ast::{Item, Lit};
use crate::check::{
    compile_body, Compiled, Ctx, Mode, Origin, StructDef, UnionDef, Word, WordId, WordKind,
};
use crate::diag::{codes, Diagnostic, Location};
use crate::graph::{Edge, Graph};
use crate::lexer::lex;
use crate::module::{assemble, ModuleOptions};
use crate::parser::parse_with;
use crate::prims;
use crate::types::{names, width_all, Effect, Ty};
use wasm_encoder::Instruction as I;

pub const PRELUDE: &str = include_str!("prelude.chasm");
pub const PRELUDE_NAME: &str = "<prelude>";

#[derive(Debug, Clone)]
pub struct Source {
    pub name: String,
    pub text: String,
}

impl Source {
    pub fn new(name: impl Into<String>, text: impl Into<String>) -> Self {
        Source {
            name: name.into(),
            text: text.into(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Options {
    pub prelude: bool,
    /// Export test thunks as `__test_N`.
    pub test_exports: bool,
    /// Whole-program export (`build`, `run`): keep only the words `main` and
    /// the `export` words reach, and refuse reachable unresolved words.
    pub export: bool,
    /// Import WASI preview1 in place of the ring host and export `_start`.
    pub wasi: bool,
}

impl Default for Options {
    fn default() -> Self {
        Options {
            prelude: true,
            test_exports: false,
            export: false,
            wasi: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "type", content = "value", rename_all = "lowercase")]
pub enum Value {
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
    Str(String),
    /// A struct value read by the host, fields in declaration order.
    Struct {
        name: String,
        fields: Vec<(String, Value)>,
    },
    Null,
    /// A rendering the host has already settled: `<n elements>`, `#slot`,
    /// or `name{...}` past the nesting limit.
    Opaque(String),
}

impl std::fmt::Display for Value {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Value::I32(v) => write!(f, "{v}"),
            Value::I64(v) => write!(f, "{v} i64"),
            Value::F32(v) => write!(f, "{v:?}f32"),
            Value::F64(v) => write!(f, "{v:?}"),
            Value::Str(s) => write!(f, "{s:?}"),
            Value::Struct { name, fields } => {
                write!(f, "{name}{{")?;
                for (k, (n, v)) in fields.iter().enumerate() {
                    if k > 0 {
                        write!(f, ", ")?;
                    }
                    write!(f, "{n}: {v}")?;
                }
                write!(f, "}}")
            }
            Value::Null => write!(f, "null"),
            Value::Opaque(s) => write!(f, "{s}"),
        }
    }
}

impl From<&Lit> for Value {
    fn from(l: &Lit) -> Self {
        match l {
            Lit::I32(v) => Value::I32(*v),
            Lit::I64(v) => Value::I64(*v),
            Lit::F32(v) => Value::F32(*v),
            Lit::F64(v) => Value::F64(*v),
            Lit::Str(s) => Value::Str(s.clone()),
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct WordInfo {
    pub name: String,
    pub effect: String,
    pub inputs: Vec<String>,
    pub outputs: Vec<String>,
    pub resolved: bool,
    /// The body failed to check; an error was reported.
    pub failed: bool,
    pub export: bool,
    pub library: bool,
    /// Generated by a `struct` declaration.
    pub generated: bool,
    /// Generic: its effect has type variables.
    pub generic: bool,
    /// The effect was inferred, not written.
    pub inferred: bool,
    /// For a generic instance (`twice<i32>`): its template's name.
    pub instance_of: Option<String>,
    pub location: Location,
}

#[derive(Debug, Clone, Serialize)]
pub struct TestInfo {
    pub index: usize,
    pub word: String,
    /// Export name of the thunk in a module built with `test_exports`.
    pub export_name: String,
    pub expected: Vec<Value>,
    pub types: Vec<String>,
    pub pending: bool,
    pub location: Location,
    #[serde(skip)]
    pub result_types: Vec<Ty>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Compilation {
    pub diagnostics: Vec<Diagnostic>,
    #[serde(skip)]
    pub wasm: Option<Vec<u8>>,
    pub words: Vec<WordInfo>,
    pub tests: Vec<TestInfo>,
    pub graph: Graph,
    pub has_main: bool,
}

impl Compilation {
    pub fn ok(&self) -> bool {
        !self.diagnostics.iter().any(Diagnostic::is_error)
    }

    pub fn word(&self, name: &str) -> Option<&WordInfo> {
        self.words.iter().find(|w| w.name == name)
    }

    /// User words that `main` and the `export` words cannot reach through
    /// call or address-taken edges; tests do not keep a word alive. Library
    /// and struct-generated words are never reported. `None` when the
    /// program has no root.
    pub fn dead(&self) -> Option<Vec<&WordInfo>> {
        let roots: Vec<&str> = self
            .words
            .iter()
            .filter(|w| w.export || (w.name == "main" && self.has_main))
            .map(|w| w.name.as_str())
            .collect();
        if roots.is_empty() {
            return None;
        }
        let live = self.graph.reachable(roots);
        Some(
            self.words
                .iter()
                .filter(|w| !w.library && !w.generated && !live.contains(&w.name))
                .collect(),
        )
    }

    /// Declared user words with no body yet.
    pub fn unresolved(&self) -> Vec<&WordInfo> {
        self.words
            .iter()
            .filter(|w| !w.resolved && !w.failed && !w.library && w.instance_of.is_none())
            .collect()
    }
}

pub fn compile(sources: &[Source], opts: &Options) -> Compilation {
    let mut ctx = Ctx::default();
    let mut diags = Vec::new();

    let mut all: Vec<(Source, Origin)> = Vec::new();
    if opts.prelude {
        all.push((Source::new(PRELUDE_NAME, PRELUDE), Origin::Library));
    }
    all.extend(sources.iter().cloned().map(|s| (s, Origin::User)));

    // Parse everything first so "used before defined" can be explained.
    let mut parsed = Vec::new();
    let mut known: HashMap<String, usize> = HashMap::new();
    for (src, origin) in &all {
        let items = lex(&src.name, &src.text).and_then(|t| parse_with(&src.name, &t, &known));
        match items {
            Ok(items) => {
                for it in &items {
                    if let Item::Struct { name, params, .. } | Item::Union { name, params, .. } = it
                    {
                        known.insert(name.clone(), params.len());
                    }
                }
                register_names(&mut ctx, &items);
                parsed.push((items, *origin));
            }
            Err(d) => diags.push(d),
        }
    }

    {
        let mut groups: Vec<&mut Vec<Item>> = parsed.iter_mut().map(|(items, _)| items).collect();
        crate::infer::require_effects(&mut groups, &mut diags);
    }
    let mut prog = Program {
        diagnostics: diags,
        ..Program::default()
    };
    ctx.defer_library_generics = true;
    for (items, origin) in parsed {
        for item in items {
            process_item(&mut ctx, item, origin, &mut prog);
        }
    }
    // Templates nothing used come last, after every other word.
    ctx.make_lazy_words();
    let Program {
        diagnostics: mut diags,
        mut tests,
        test_words,
    } = prog;

    // main must be ( -- ).
    let has_main = match ctx.by_name.get("main") {
        Some(&id) => {
            let w = &ctx.words[id];
            if !w.effect.inputs.is_empty() || !w.effect.outputs.is_empty() {
                diags.push(
                    Diagnostic::error(
                        codes::E_MAIN_EFFECT,
                        format!(
                            "`main` must have effect ( -- ) but is declared {}",
                            w.effect
                        ),
                        w.loc.clone(),
                    )
                    .with_word("main"),
                );
            }
            true
        }
        None => false,
    };

    for t in &mut tests {
        // Tests may also name primitives, which are never pending.
        t.pending = ctx
            .by_name
            .get(&t.word)
            .is_some_and(|&id| ctx.words[id].body.is_none());
    }

    let graph = graph_of(&ctx);
    let words = ctx
        .words
        .iter()
        .filter(|w| matches!(w.kind, WordKind::Named | WordKind::Instance))
        .map(|w| WordInfo {
            name: w.name.clone(),
            effect: w.effect.to_string(),
            inputs: names(&w.effect.inputs),
            outputs: names(&w.effect.outputs),
            resolved: w.body.is_some(),
            failed: w.failed,
            export: w.export,
            library: w.origin == Origin::Library,
            generated: w.generated.is_some(),
            generic: w.generic.is_some(),
            inferred: w.inferred,
            instance_of: w
                .instance_of
                .as_ref()
                .map(|(t, _)| ctx.words[*t].name.clone()),
            location: w.loc.clone(),
        })
        .collect();

    let live = if opts.export {
        live_words(&ctx, &graph, &mut diags)
    } else {
        None
    };

    let ok = !diags.iter().any(Diagnostic::is_error);
    let wasm = if ok {
        let test_exports = if opts.test_exports {
            tests
                .iter()
                .zip(&test_words)
                .map(|(t, &id)| (t.export_name.clone(), id))
                .collect()
        } else {
            Vec::new()
        };
        let bytes = assemble(
            &mut ctx,
            &ModuleOptions {
                test_exports,
                live,
                wasi: opts.wasi,
            },
        );
        match validate(&bytes) {
            Ok(()) => Some(bytes),
            Err(e) => {
                diags.push(Diagnostic::error(
                    codes::E_INTERNAL,
                    format!("compiler produced an invalid module (this is a compiler bug): {e}"),
                    Location::default(),
                ));
                None
            }
        }
    } else {
        None
    };

    Compilation {
        diagnostics: diags,
        wasm,
        words,
        tests,
        graph,
        has_main,
    }
}

/// Program state the per-item rules accumulate into.
#[derive(Default, Clone)]
pub(crate) struct Program {
    pub diagnostics: Vec<Diagnostic>,
    pub tests: Vec<TestInfo>,
    pub test_words: Vec<WordId>,
}

/// Record every name the items define or declare, for "used before it is
/// defined" messages.
pub(crate) fn register_names(ctx: &mut Ctx, items: &[Item]) {
    for it in items {
        match it {
            Item::Def { name, .. } | Item::Declare { name, .. } => {
                ctx.all_names.insert(name.clone());
            }
            Item::Struct {
                name,
                params,
                fields,
                ..
            } => {
                ctx.all_names.insert(name.clone());
                let plain: Vec<(String, Ty)> = fields
                    .iter()
                    .map(|(n, t, _)| (n.clone(), t.clone()))
                    .collect();
                for (w, _, _) in struct_words(name, params, &plain, 0) {
                    ctx.all_names.insert(w);
                }
            }
            Item::Union { name, .. } => {
                ctx.all_names.insert(name.clone());
            }
            Item::Test { .. } => {}
        }
    }
}

/// Apply one top-level form: declare, define or redefine a word, or record a
/// test. Returns the word id when a word got a body or was newly declared.
pub(crate) fn process_item(
    ctx: &mut Ctx,
    item: Item,
    origin: Origin,
    p: &mut Program,
) -> Vec<WordId> {
    // A definition named like a pending prelude template meets the
    // template, and a test of one makes it.
    if let Item::Def { name, .. } | Item::Declare { name, .. } | Item::Test { word: name, .. } =
        &item
    {
        ctx.lookup(name);
    }
    match item {
        Item::Declare { name, effect, loc } => {
            if let Some(d) = check_new_name(&name, &loc) {
                p.diagnostics.push(d);
                return vec![];
            }
            if let Err(d) = check_effect_types(ctx, &effect, &loc) {
                p.diagnostics.push(d.with_word(&name));
                return vec![];
            }
            match ctx.by_name.get(&name) {
                Some(&id) => {
                    if ctx.words[id].effect != effect {
                        p.diagnostics.push(
                            Diagnostic::error(
                                codes::E_DECLARE_MISMATCH,
                                format!(
                                    "`{name}` is already declared {} and cannot be declared {effect}",
                                    ctx.words[id].effect
                                ),
                                loc,
                            )
                            .with_word(&name),
                        );
                    }
                }
                None => {
                    let generic = effect.is_generic();
                    let mut w = new_word(name, effect, origin, WordKind::Named, loc);
                    if generic {
                        w.generic = Some(crate::check::Generic { body: None });
                    }
                    return vec![ctx.add_word(w)];
                }
            }
            vec![]
        }
        Item::Def {
            name,
            effect,
            body,
            export,
            loc,
        } => {
            if let Some(d) = check_new_name(&name, &loc) {
                p.diagnostics.push(d);
                return vec![];
            }
            let inferred = effect.is_none();
            let effect = match effect {
                Some(e) => e,
                None => match crate::infer::infer_effect(ctx, &name, &body, &loc) {
                    Ok(e) => e,
                    Err(d) => {
                        p.diagnostics.push(d.with_word(&name));
                        return vec![];
                    }
                },
            };
            if let Err(d) = check_effect_types(ctx, &effect, &loc) {
                p.diagnostics.push(d.with_word(&name));
                return vec![];
            }
            let generic = effect.is_generic();
            if generic && export {
                p.diagnostics.push(
                    Diagnostic::error(
                        codes::E_NEEDS_EFFECT,
                        format!("`{name}` is exported, so its effect must be concrete; {effect} has type variables"),
                        loc,
                    )
                    .with_word(&name),
                );
                return vec![];
            }
            // A prelude generic word is made on first use, so a program that
            // never uses it keeps its numbering. The REPL processes the
            // prelude eagerly, which is where its templates are checked.
            if generic
                && !inferred
                && origin == Origin::Library
                && ctx.defer_library_generics
                && !ctx.by_name.contains_key(&name)
            {
                ctx.lazy_words.insert(
                    name.clone(),
                    crate::check::LazyWord {
                        ty: name.clone(),
                        group: vec![name],
                        effect,
                        origin,
                        loc,
                        body: Some(body),
                    },
                );
                return vec![];
            }
            let id = match ctx.by_name.get(&name) {
                Some(&id) => {
                    let w = &ctx.words[id];
                    if w.effect != effect {
                        let dependants = graph_of(ctx).callers(&name);
                        let (code, what) = if w.body.is_none() && !w.failed {
                            (codes::E_DECLARE_MISMATCH, "declared")
                        } else {
                            (codes::E_REDEFINE_EFFECT, "defined")
                        };
                        let mut d = Diagnostic::error(
                            code,
                            format!(
                                "`{name}` is {what} {} but this definition has effect {effect}; an effect can only change deliberately",
                                w.effect
                            ),
                            loc,
                        )
                        .with_word(&name);
                        d.declared_effect = Some(w.effect.to_string());
                        d.dependants = Some(dependants);
                        p.diagnostics.push(d);
                        return vec![];
                    }
                    id
                }
                None => ctx.add_word(new_word(
                    name.clone(),
                    effect.clone(),
                    origin,
                    WordKind::Named,
                    loc.clone(),
                )),
            };
            if export {
                ctx.words[id].export = true;
            }
            if generic {
                let built = define_template(ctx, id, &name, &effect, body, loc, p);
                ctx.words[id].inferred = inferred;
                return built;
            }
            match compile_body(ctx, &name, Mode::Declared(&effect), &body, &loc, &[]) {
                Ok(out) => {
                    let w = &mut ctx.words[id];
                    w.body = Some(out.compiled);
                    w.callees = out.callees;
                    w.failed = false;
                    w.loc = loc;
                    w.inferred = inferred;
                    vec![id]
                }
                Err(d) => {
                    ctx.words[id].failed = true;
                    p.diagnostics.push(d);
                    vec![]
                }
            }
        }
        Item::Struct {
            name,
            params,
            fields,
            loc,
        } => define_struct(ctx, name, params, fields, loc, origin, p),
        Item::Union {
            name,
            params,
            variants,
            loc,
        } => define_union(ctx, name, params, variants, loc, origin, p),
        Item::Test {
            word,
            body,
            expected,
            loc,
        } => {
            if !ctx.by_name.contains_key(&word) && !prims::is_builtin(&word) {
                let msg = if ctx.all_names.contains(&word) {
                    format!("test of `{word}` comes before `{word}` is defined; move the test below it or `declare` the word first")
                } else {
                    format!(
                        "test names unknown word `{word}`{}",
                        prims::suggest(&word, ctx.by_name.keys().map(String::as_str))
                    )
                };
                p.diagnostics
                    .push(Diagnostic::error(codes::E_UNDEFINED, msg, loc));
                return vec![];
            }
            let index = p.tests.len();
            let tname = format!("[test {word} #{index}]");
            let out = match compile_body(ctx, &tname, Mode::Derived, &body, &loc, &[]) {
                Ok(o) => o,
                Err(d) => {
                    p.diagnostics.push(d);
                    return vec![];
                }
            };
            let want: Vec<Ty> = expected.iter().map(|(l, _)| l.ty()).collect();
            if want != out.effect.outputs {
                p.diagnostics.push(
                    Diagnostic::error(
                        codes::E_TEST_TYPE,
                        format!(
                            "test of `{word}` expects ( {} ) but its body leaves ( {} )",
                            names(&want).join(" "),
                            names(&out.effect.outputs).join(" ")
                        ),
                        loc,
                    )
                    .with_word(&word)
                    .with_stacks(names(&want), names(&out.effect.outputs)),
                );
                return vec![];
            }
            let tid = ctx.add_word(Word {
                name: tname,
                effect: out.effect.clone(),
                body: Some(out.compiled),
                failed: false,
                export: false,
                origin,
                kind: WordKind::Test,
                loc: loc.clone(),
                callees: out.callees,
                inferred: false,
                generic: None,
                instance_of: None,
                generated: None,
            });
            p.test_words.push(tid);
            p.tests.push(TestInfo {
                index,
                word,
                export_name: format!("__test_{index}"),
                expected: expected.iter().map(|(l, _)| Value::from(l)).collect(),
                types: names(&want),
                pending: false,
                location: loc,
                result_types: want,
            });
            vec![]
        }
    }
}

/// The words a struct declaration generates, with their effects and code:
/// `s.new`, then `s.f` and `s.f!` for each field.
pub(crate) fn struct_words(
    name: &str,
    params: &[String],
    fields: &[(String, Ty)],
    idx: u32,
) -> Vec<(String, Effect, Vec<I<'static>>)> {
    let me = Ty::Struct(
        name.to_string(),
        params.iter().map(|p| Ty::Param(p.clone())).collect(),
    );
    let tys: Vec<Ty> = fields.iter().map(|(_, t)| t.clone()).collect();
    let mut code: Vec<I> = (0..width_all(&tys)).map(I::LocalGet).collect();
    code.push(I::StructNew(idx));
    let mut out = vec![(
        format!("{name}.new"),
        Effect::new(tys, vec![me.clone()]),
        code,
    )];
    let mut w = 0;
    for (f, t) in fields {
        let (mut get, mut set) = (Vec::new(), Vec::new());
        for j in 0..t.width() {
            let field = I::StructGet {
                struct_type_index: idx,
                field_index: w + j,
            };
            get.extend([I::LocalGet(0), field]);
            set.extend([
                I::LocalGet(0),
                I::LocalGet(1 + j),
                I::StructSet {
                    struct_type_index: idx,
                    field_index: w + j,
                },
            ]);
        }
        w += t.width();
        out.push((
            format!("{name}.{f}"),
            Effect::new(vec![me.clone()], vec![t.clone()]),
            get,
        ));
        out.push((
            format!("{name}.{f}!"),
            Effect::new(vec![me.clone(), t.clone()], vec![]),
            set,
        ));
    }
    out
}

fn render_fields(fields: &[(String, Ty)]) -> String {
    let parts: Vec<String> = fields.iter().map(|(n, t)| format!("{n}: {t}")).collect();
    format!("( {} )", parts.join(" "))
}

/// `struct name  field: type ...`: register the WasmGC type and define the
/// generated words. Identical redeclaration is a no-op; changed fields are
/// rejected like a changed effect.
fn define_struct(
    ctx: &mut Ctx,
    name: String,
    params: Vec<String>,
    fields: Vec<(String, Ty, Location)>,
    loc: Location,
    origin: Origin,
    p: &mut Program,
) -> Vec<WordId> {
    if let Some(d) = check_type_name(&name, &loc) {
        p.diagnostics.push(d);
        return vec![];
    }
    for (field, ty, floc) in &fields {
        let unknown: Vec<String> = Effect::new(vec![ty.clone()], vec![])
            .params()
            .into_iter()
            .filter(|t| !params.contains(t))
            .collect();
        if let Some(t) = unknown.first() {
            let msg = if params.is_empty() {
                format!("field `{field}` of struct `{name}` has type {ty}: `{t}` is a type variable, and `{name}` has no type parameters; declare them after the name, `struct {name} {t}  ...`")
            } else {
                format!(
                    "field `{field}` of struct `{name}` has type {ty}: `{t}` is not one of its type parameters ({})",
                    params.join(" ")
                )
            };
            p.diagnostics
                .push(Diagnostic::error(codes::E_UNKNOWN_TYPE, msg, floc.clone()));
            return vec![];
        }
        if !self_application(&name, &params, ty) {
            p.diagnostics.push(Diagnostic::error(
                codes::E_UNKNOWN_TYPE,
                format!(
                    "field `{field}` of struct `{name}` has type {ty}: a generic type may name itself only as `{}`",
                    Ty::Struct(name.clone(), params.iter().map(|p| Ty::Param(p.clone())).collect())
                ),
                floc.clone(),
            ));
            return vec![];
        }
        if let Err(d) = ctx.check_types(std::slice::from_ref(ty), floc, Some(&name)) {
            p.diagnostics.push(d);
            return vec![];
        }
    }
    if ctx.union_by_name.contains_key(&name) {
        p.diagnostics.push(Diagnostic::error(
            codes::E_REDEFINE_EFFECT,
            format!("`{name}` is already declared as a union and cannot become a struct"),
            loc,
        ));
        return vec![];
    }
    let plain: Vec<(String, Ty)> = fields.into_iter().map(|(n, t, _)| (n, t)).collect();
    if let Some(&k) = ctx.struct_by_name.get(&name) {
        let old = ctx.structs[k].fields.clone();
        if old == plain && ctx.structs[k].params == params {
            return vec![];
        }
        let graph = graph_of(ctx);
        let mut deps: Vec<String> = Vec::new();
        for (w, _, _) in struct_words(&name, &ctx.structs[k].params.clone(), &old, 0) {
            for c in graph.callers(&w) {
                if !deps.contains(&c) {
                    deps.push(c);
                }
            }
        }
        let mut d = Diagnostic::error(
            codes::E_REDEFINE_EFFECT,
            format!(
                "struct `{name}` is already declared with fields {} and cannot change",
                render_fields(&old)
            ),
            loc,
        );
        d.declared_effect = Some(render_fields(&old));
        d.dependants = Some(deps);
        p.diagnostics.push(d);
        return vec![];
    }
    // A generated name already taken with another effect blocks the struct.
    let preview = struct_words(&name, &params, &plain, 0);
    for (w, effect, _) in &preview {
        if let Some(&id) = ctx.by_name.get(w) {
            if ctx.words[id].effect != *effect {
                let mut d = Diagnostic::error(
                    codes::E_REDEFINE_EFFECT,
                    format!(
                        "`{w}` is defined {} but struct `{name}` generates it as {effect}",
                        ctx.words[id].effect
                    ),
                    loc,
                )
                .with_word(w);
                d.declared_effect = Some(ctx.words[id].effect.to_string());
                d.dependants = Some(graph_of(ctx).callers(w));
                p.diagnostics.push(d);
                return vec![];
            }
        }
    }
    ctx.struct_by_name.insert(name.clone(), ctx.structs.len());
    ctx.structs.push(StructDef {
        name: name.clone(),
        params: params.clone(),
        fields: plain.clone(),
        type_index: 0,
        loc: loc.clone(),
    });
    let generic = !params.is_empty();
    // A generic struct registers no type: each instantiation is its own.
    let idx = if generic {
        0
    } else {
        let idx = ctx
            .register_type(&Ty::Struct(name.clone(), Vec::new()))
            .expect("a declared struct registers");
        let k = ctx.struct_by_name[&name];
        ctx.structs[k].type_index = idx;
        idx
    };
    let words = struct_words(&name, &params, &plain, idx);
    if generic && origin == Origin::Library && ctx.defer_library_generics {
        defer_generated(ctx, &name, words, origin, &loc);
        return vec![];
    }
    let mut ids = Vec::new();
    for (w, effect, code) in words {
        let id = match ctx.by_name.get(&w) {
            Some(&id) => id,
            None => ctx.add_word(new_word(
                w.clone(),
                effect,
                origin,
                WordKind::Named,
                loc.clone(),
            )),
        };
        let code = if generic {
            crate::check::template_code(ctx, &w)
        } else {
            code
        };
        let word = &mut ctx.words[id];
        word.body = Some(Compiled {
            locals: vec![],
            code,
        });
        word.failed = false;
        word.loc = loc.clone();
        word.generated = Some(name.clone());
        if generic {
            word.generic = Some(crate::check::Generic { body: None });
        }
        ids.push(id);
    }
    ids
}

/// Defer the generated words of a prelude generic type until first use
/// (`Ctx::lookup`), so a program that never uses them keeps its numbering.
fn defer_generated(
    ctx: &mut Ctx,
    ty: &str,
    words: Vec<(String, Effect, Vec<I<'static>>)>,
    origin: Origin,
    loc: &Location,
) {
    let group: Vec<String> = words.iter().map(|(w, _, _)| w.clone()).collect();
    for (w, effect, _) in words {
        ctx.lazy_words.insert(
            w,
            crate::check::LazyWord {
                ty: ty.to_string(),
                group: group.clone(),
                effect,
                origin,
                loc: loc.clone(),
                body: None,
            },
        );
    }
}

/// A generic type may name itself in its fields only applied to its own
/// parameters in order (`list T` in `union list T`).
fn self_application(name: &str, params: &[String], t: &Ty) -> bool {
    match t {
        Ty::Struct(n, args) => {
            (n != name
                || args.len() == params.len()
                    && args
                        .iter()
                        .zip(params)
                        .all(|(a, p)| *a == Ty::Param(p.clone())))
                && args.iter().all(|a| self_application(name, params, a))
        }
        Ty::Array(e) => self_application(name, params, e),
        Ty::Quot(e) => e
            .inputs
            .iter()
            .chain(&e.outputs)
            .all(|t| self_application(name, params, t)),
        _ => true,
    }
}

pub fn validate(bytes: &[u8]) -> Result<(), String> {
    wasmparser::Validator::new()
        .validate_all(bytes)
        .map(|_| ())
        .map_err(|e| e.to_string())
}

/// A generic word: check the body once with its type parameters rigid, keep
/// the body as the template, and give the word a placeholder that traps (it
/// is never called: callers reach instances).
fn define_template(
    ctx: &mut Ctx,
    id: WordId,
    name: &str,
    effect: &Effect,
    body: crate::ast::Body,
    loc: Location,
    p: &mut Program,
) -> Vec<WordId> {
    if let Err(d) = crate::check::check_body(ctx, name, Mode::Declared(effect), &body, &loc, &[]) {
        let w = &mut ctx.words[id];
        w.failed = true;
        // Still generic, so callers instantiate it rather than misread `T`.
        w.generic
            .get_or_insert(crate::check::Generic { body: None });
        p.diagnostics.push(d);
        return vec![];
    }
    let code = crate::check::template_code(ctx, name);
    let w = &mut ctx.words[id];
    w.body = Some(Compiled {
        locals: Vec::new(),
        code,
    });
    w.callees = Vec::new();
    w.failed = false;
    w.loc = loc;
    w.generic = Some(crate::check::Generic { body: Some(body) });
    // Instances made from an earlier body are rebuilt in place, so callers
    // (through the table at the REPL) reach the new code.
    let mut instances: Vec<WordId> = ctx
        .instances
        .iter()
        .filter(|((t, _), _)| *t == id)
        .map(|(_, &inst)| inst)
        .collect();
    instances.sort();
    let mut built = vec![id];
    for inst in instances {
        match crate::check::compile_instance(ctx, inst) {
            Ok(()) => built.push(inst),
            Err(d) => p.diagnostics.push(d),
        }
    }
    built
}

pub(crate) fn new_word(
    name: String,
    effect: Effect,
    origin: Origin,
    kind: WordKind,
    loc: Location,
) -> Word {
    Word {
        name,
        effect,
        body: None,
        failed: false,
        export: false,
        origin,
        kind,
        loc,
        callees: Vec::new(),
        inferred: false,
        generic: None,
        instance_of: None,
        generated: None,
    }
}

/// Check the types an effect names, and register the concrete struct and
/// union types among them.
fn check_effect_types(ctx: &mut Ctx, e: &Effect, loc: &Location) -> Result<(), Diagnostic> {
    ctx.check_types(&e.inputs, loc, None)?;
    ctx.check_types(&e.outputs, loc, None)?;
    ctx.register_effect(e);
    Ok(())
}

/// A struct or union name: the syntax rules of a word name, but it may be a
/// primitive's name, since types and words are separate namespaces.
fn check_type_name(name: &str, loc: &Location) -> Option<Diagnostic> {
    if prims::is_builtin(name) {
        return None;
    }
    check_new_name(name, loc)
}

pub(crate) fn check_new_name(name: &str, loc: &Location) -> Option<Diagnostic> {
    if prims::is_builtin(name)
        || matches!(name, ":>" | "[" | "]" | "(" | ")" | ";" | ":" | "--" | "->")
    {
        return Some(Diagnostic::error(
            codes::E_REDEFINE_EFFECT,
            format!("`{name}` is a primitive and cannot be defined or declared"),
            loc.clone(),
        ));
    }
    if crate::parser::parse_number(name).is_some() || name.starts_with('\'') {
        return Some(Diagnostic::error(
            codes::E_SYNTAX,
            format!("`{name}` is not a valid word name"),
            loc.clone(),
        ));
    }
    None
}

/// The ids of the words `main` and the `export` words reach, following call
/// and address-taken edges. Reports every reachable word that is declared
/// but has no body. `None` when there is no root: nothing is trimmed.
fn live_words(ctx: &Ctx, graph: &Graph, diags: &mut Vec<Diagnostic>) -> Option<HashSet<WordId>> {
    let roots: Vec<&str> = ctx
        .words
        .iter()
        .filter(|w| w.kind == WordKind::Named && (w.export || w.name == "main"))
        .map(|w| w.name.as_str())
        .collect();
    if roots.is_empty() {
        return None;
    }
    let names = graph.reachable(roots.iter().copied());
    let mut live = HashSet::new();
    for (id, w) in ctx.words.iter().enumerate() {
        if w.kind == WordKind::Test || !names.contains(&w.name) {
            continue;
        }
        // A generic template has no concrete type: callers reach its
        // instances, so it stays out of the module (its slot stays null).
        // An unresolved template is still reported, once, below.
        if w.generic.is_none() {
            live.insert(id);
        }
        if w.kind == WordKind::Named && w.body.is_none() && !w.failed {
            let mut d =
                Diagnostic::error(
                    codes::E_UNRESOLVED,
                    format!(
                    "`{}` is declared {} but has no body, and {} {} it; define it before building",
                    w.name,
                    w.effect,
                    roots.iter().map(|r| format!("`{r}`")).collect::<Vec<_>>().join(", "),
                    if roots.len() == 1 { "reaches" } else { "reach" }
                ),
                    w.loc.clone(),
                )
                .with_word(&w.name);
            d.declared_effect = Some(w.effect.to_string());
            d.dependants = Some(graph.callers(&w.name));
            diags.push(d);
        }
    }
    Some(live)
}

pub(crate) fn graph_of(ctx: &Ctx) -> Graph {
    let mut g = Graph::default();
    for w in &ctx.words {
        if w.kind == WordKind::Test {
            continue;
        }
        let edges = w.callees.iter().map(|&(id, kind)| Edge {
            word: ctx.words[id].name.clone(),
            kind,
        });
        g.set_callees(&w.name, edges);
    }
    g
}

/// A union declaration (`union shape | circle  r: f64 | empty`): checked
/// like a struct, registered as a WasmGC supertype with a final subtype per
/// variant, and given its generated words.
fn define_union(
    ctx: &mut Ctx,
    name: String,
    params: Vec<String>,
    variants: Vec<crate::ast::Variant>,
    loc: Location,
    origin: Origin,
    p: &mut Program,
) -> Vec<WordId> {
    if let Some(d) = check_type_name(&name, &loc) {
        p.diagnostics.push(d);
        return vec![];
    }
    if ctx.struct_by_name.contains_key(&name) {
        p.diagnostics.push(Diagnostic::error(
            codes::E_REDEFINE_EFFECT,
            format!("`{name}` is already declared as a struct and cannot become a union"),
            loc,
        ));
        return vec![];
    }
    for v in &variants {
        for (field, ty, floc) in &v.fields {
            let unknown: Vec<String> = Effect::new(vec![ty.clone()], vec![])
                .params()
                .into_iter()
                .filter(|t| !params.contains(t))
                .collect();
            if let Some(t) = unknown.first() {
                p.diagnostics.push(Diagnostic::error(
                    codes::E_UNKNOWN_TYPE,
                    format!("field `{field}` of `{name}.{}` has type {ty}: `{t}` is not one of the type parameters of `{name}`", v.name),
                    floc.clone(),
                ));
                return vec![];
            }
            if !self_application(&name, &params, ty) {
                p.diagnostics.push(Diagnostic::error(
                    codes::E_UNKNOWN_TYPE,
                    format!(
                        "field `{field}` of `{name}.{}` has type {ty}: a generic type may name itself only as `{}`",
                        v.name,
                        Ty::Struct(name.clone(), params.iter().map(|p| Ty::Param(p.clone())).collect())
                    ),
                    floc.clone(),
                ));
                return vec![];
            }
            if let Err(d) = ctx.check_types(std::slice::from_ref(ty), floc, Some(&name)) {
                p.diagnostics.push(d);
                return vec![];
            }
        }
    }
    let plain: Vec<(String, Vec<(String, Ty)>)> = variants
        .into_iter()
        .map(|v| {
            (
                v.name,
                v.fields.into_iter().map(|(n, t, _)| (n, t)).collect(),
            )
        })
        .collect();
    if let Some(&k) = ctx.union_by_name.get(&name) {
        let old = &ctx.unions[k];
        if old.variants == plain && old.params == params {
            return vec![];
        }
        let graph = graph_of(ctx);
        let mut deps: Vec<String> = Vec::new();
        for w in union_word_names(old) {
            for c in graph.callers(&w) {
                if !deps.contains(&c) {
                    deps.push(c);
                }
            }
        }
        let mut d = Diagnostic::error(
            codes::E_REDEFINE_EFFECT,
            format!("union `{name}` is already declared with other variants and cannot change"),
            loc,
        );
        d.dependants = Some(deps);
        p.diagnostics.push(d);
        return vec![];
    }
    let k = ctx.unions.len();
    ctx.union_by_name.insert(name.clone(), k);
    let generic = !params.is_empty();
    ctx.unions.push(UnionDef {
        name: name.clone(),
        params,
        variants: plain,
        type_index: 0,
        loc: loc.clone(),
    });
    // A generic union registers no type: each instantiation is its own.
    let idx = if generic {
        0
    } else {
        let idx = ctx
            .register_type(&Ty::Struct(name.clone(), Vec::new()))
            .expect("a declared union registers");
        ctx.unions[k].type_index = idx;
        idx
    };
    let def = ctx.unions[k].clone();
    let words = union_words(ctx, &def, idx, !generic);
    if generic && origin == Origin::Library && ctx.defer_library_generics {
        defer_generated(ctx, &name, words, origin, &loc);
        return vec![];
    }
    let mut ids = Vec::new();
    for (w, effect, code) in words {
        let id = match ctx.by_name.get(&w) {
            Some(&id) => id,
            None => ctx.add_word(new_word(
                w.clone(),
                effect,
                origin,
                WordKind::Named,
                loc.clone(),
            )),
        };
        let code = if generic {
            crate::check::template_code(ctx, &w)
        } else {
            code
        };
        let word = &mut ctx.words[id];
        word.body = Some(Compiled {
            locals: vec![],
            code,
        });
        word.failed = false;
        word.loc = loc.clone();
        word.generated = Some(name.clone());
        if generic {
            word.generic = Some(crate::check::Generic { body: None });
        }
        ids.push(id);
    }
    ids
}

/// The words a union generates: a constructor per variant, `u.v`, taking its
/// fields in order; `u.tag`, the variant's index; and a reader per field of
/// each variant, `u.v.f`, which traps on another variant.
///
/// Without `emit` (a generic union's templates) only names and effects are
/// meaningful, and no literal is interned.
pub(crate) fn union_words(
    ctx: &mut Ctx,
    def: &UnionDef,
    idx: u32,
    emit: bool,
) -> Vec<(String, Effect, Vec<I<'static>>)> {
    use wasm_encoder::{BlockType, HeapType, ValType};
    let u = &def.name;
    let me = Ty::Struct(
        u.clone(),
        def.params.iter().map(|p| Ty::Param(p.clone())).collect(),
    );
    let variant = |k: usize| idx + 1 + k as u32;
    let mut out = Vec::new();
    for (k, (v, fields)) in def.variants.iter().enumerate() {
        let tys: Vec<Ty> = fields.iter().map(|(_, t)| t.clone()).collect();
        let mut code: Vec<I> = (0..width_all(&tys)).map(I::LocalGet).collect();
        code.push(I::StructNew(variant(k)));
        out.push((format!("{u}.{v}"), Effect::new(tys, vec![me.clone()]), code));
    }
    // tag: a null traps; then test each variant but the last in order.
    let n = def.variants.len();
    let mut tag = vec![I::LocalGet(0), I::RefAsNonNull, I::Drop];
    for k in 0..n - 1 {
        tag.extend([
            I::LocalGet(0),
            I::RefTestNonNull(HeapType::Concrete(variant(k))),
            I::If(BlockType::Result(ValType::I32)),
            I::I32Const(k as i32),
            I::Else,
        ]);
    }
    tag.push(I::I32Const(n as i32 - 1));
    tag.extend((0..n - 1).map(|_| I::End));
    out.push((
        format!("{u}.tag"),
        Effect::new(vec![me.clone()], vec![Ty::I32]),
        tag,
    ));
    for (k, (v, fields)) in def.variants.iter().enumerate() {
        let mut w = 0;
        for (f, t) in fields {
            let name = format!("{u}.{v}.{f}");
            if !emit {
                out.push((
                    name,
                    Effect::new(vec![me.clone()], vec![t.clone()]),
                    Vec::new(),
                ));
                continue;
            }
            let (ma, ml) = ctx.intern_str(&format!("{name}: not a {v}"));
            let (wa, wl) = ctx.intern_str(&name);
            let mut code = vec![
                I::LocalGet(0),
                I::RefAsNonNull,
                I::Drop,
                I::LocalGet(0),
                I::RefTestNonNull(HeapType::Concrete(variant(k))),
                I::I32Eqz,
                I::If(BlockType::Empty),
                I::I32Const(ma),
                I::I32Const(ml),
                I::I32Const(wa),
                I::I32Const(wl),
                I::Call(crate::check::FN_TRAP),
                I::Unreachable,
                I::End,
            ];
            for j in 0..t.width() {
                code.extend([
                    I::LocalGet(0),
                    I::RefCastNonNull(HeapType::Concrete(variant(k))),
                    I::StructGet {
                        struct_type_index: variant(k),
                        field_index: w + j,
                    },
                ]);
            }
            w += t.width();
            out.push((name, Effect::new(vec![me.clone()], vec![t.clone()]), code));
        }
    }
    out
}

/// The names of the words a union generates.
fn union_word_names(def: &UnionDef) -> Vec<String> {
    let u = &def.name;
    let mut out: Vec<String> = def
        .variants
        .iter()
        .map(|(v, _)| format!("{u}.{v}"))
        .collect();
    out.push(format!("{u}.tag"));
    for (v, fields) in &def.variants {
        out.extend(fields.iter().map(|(f, _)| format!("{u}.{v}.{f}")));
    }
    out
}
